-- Expands the tradable universe from the 3-symbol smoke-test set to a few hundred
-- real, recognizable tickers across sectors, so the order ticket / watchlist / dashboard
-- have something realistic to search and browse. Fauxnance mock synthesizes quotes for
-- any symbol it doesn't have curated data for, so this list needs no matching mock entry.

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('AAPL', 'Apple Inc.', 'EQUITY', 'USD', true),
    ('MSFT', 'Microsoft Corp.', 'EQUITY', 'USD', true),
    ('GOOGL', 'Alphabet Inc. Class A', 'EQUITY', 'USD', true),
    ('GOOG', 'Alphabet Inc. Class C', 'EQUITY', 'USD', true),
    ('AMZN', 'Amazon.com Inc.', 'EQUITY', 'USD', true),
    ('META', 'Meta Platforms Inc.', 'EQUITY', 'USD', true),
    ('NVDA', 'NVIDIA Corp.', 'EQUITY', 'USD', true),
    ('TSLA', 'Tesla Inc.', 'EQUITY', 'USD', true),
    ('AVGO', 'Broadcom Inc.', 'EQUITY', 'USD', true),
    ('ORCL', 'Oracle Corp.', 'EQUITY', 'USD', true),
    ('ADBE', 'Adobe Inc.', 'EQUITY', 'USD', true),
    ('CRM', 'Salesforce Inc.', 'EQUITY', 'USD', true),
    ('AMD', 'Advanced Micro Devices Inc.', 'EQUITY', 'USD', true),
    ('INTC', 'Intel Corp.', 'EQUITY', 'USD', true),
    ('CSCO', 'Cisco Systems Inc.', 'EQUITY', 'USD', true),
    ('QCOM', 'Qualcomm Inc.', 'EQUITY', 'USD', true),
    ('TXN', 'Texas Instruments Inc.', 'EQUITY', 'USD', true),
    ('IBM', 'International Business Machines Corp.', 'EQUITY', 'USD', true),
    ('NOW', 'ServiceNow Inc.', 'EQUITY', 'USD', true),
    ('UBER', 'Uber Technologies Inc.', 'EQUITY', 'USD', true),
    ('SHOP', 'Shopify Inc.', 'EQUITY', 'USD', true),
    ('SNOW', 'Snowflake Inc.', 'EQUITY', 'USD', true),
    ('PLTR', 'Palantir Technologies Inc.', 'EQUITY', 'USD', true),
    ('NFLX', 'Netflix Inc.', 'EQUITY', 'USD', true),
    ('DIS', 'Walt Disney Co.', 'EQUITY', 'USD', true),
    ('CMCSA', 'Comcast Corp.', 'EQUITY', 'USD', true),
    ('T', 'AT&T Inc.', 'EQUITY', 'USD', true),
    ('VZ', 'Verizon Communications Inc.', 'EQUITY', 'USD', true),
    ('TMUS', 'T-Mobile US Inc.', 'EQUITY', 'USD', true),
    ('PYPL', 'PayPal Holdings Inc.', 'EQUITY', 'USD', true),
    ('SQ', 'Block Inc.', 'EQUITY', 'USD', true),
    ('INTU', 'Intuit Inc.', 'EQUITY', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('JPM', 'JPMorgan Chase & Co.', 'EQUITY', 'USD', true),
    ('BAC', 'Bank of America Corp.', 'EQUITY', 'USD', true),
    ('WFC', 'Wells Fargo & Co.', 'EQUITY', 'USD', true),
    ('C', 'Citigroup Inc.', 'EQUITY', 'USD', true),
    ('GS', 'Goldman Sachs Group Inc.', 'EQUITY', 'USD', true),
    ('MS', 'Morgan Stanley', 'EQUITY', 'USD', true),
    ('V', 'Visa Inc.', 'EQUITY', 'USD', true),
    ('MA', 'Mastercard Inc.', 'EQUITY', 'USD', true),
    ('AXP', 'American Express Co.', 'EQUITY', 'USD', true),
    ('BLK', 'BlackRock Inc.', 'EQUITY', 'USD', true),
    ('SCHW', 'Charles Schwab Corp.', 'EQUITY', 'USD', true),
    ('SPGI', 'S&P Global Inc.', 'EQUITY', 'USD', true),
    ('ICE', 'Intercontinental Exchange Inc.', 'EQUITY', 'USD', true),
    ('CME', 'CME Group Inc.', 'EQUITY', 'USD', true),
    ('AIG', 'American International Group Inc.', 'EQUITY', 'USD', true),
    ('MET', 'MetLife Inc.', 'EQUITY', 'USD', true),
    ('PRU', 'Prudential Financial Inc.', 'EQUITY', 'USD', true),
    ('TRV', 'Travelers Companies Inc.', 'EQUITY', 'USD', true),
    ('PGR', 'Progressive Corp.', 'EQUITY', 'USD', true),
    ('COF', 'Capital One Financial Corp.', 'EQUITY', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('UNH', 'UnitedHealth Group Inc.', 'EQUITY', 'USD', true),
    ('JNJ', 'Johnson & Johnson', 'EQUITY', 'USD', true),
    ('LLY', 'Eli Lilly and Co.', 'EQUITY', 'USD', true),
    ('PFE', 'Pfizer Inc.', 'EQUITY', 'USD', true),
    ('MRK', 'Merck & Co. Inc.', 'EQUITY', 'USD', true),
    ('ABBV', 'AbbVie Inc.', 'EQUITY', 'USD', true),
    ('TMO', 'Thermo Fisher Scientific Inc.', 'EQUITY', 'USD', true),
    ('ABT', 'Abbott Laboratories', 'EQUITY', 'USD', true),
    ('DHR', 'Danaher Corp.', 'EQUITY', 'USD', true),
    ('BMY', 'Bristol-Myers Squibb Co.', 'EQUITY', 'USD', true),
    ('AMGN', 'Amgen Inc.', 'EQUITY', 'USD', true),
    ('GILD', 'Gilead Sciences Inc.', 'EQUITY', 'USD', true),
    ('CVS', 'CVS Health Corp.', 'EQUITY', 'USD', true),
    ('CI', 'Cigna Group', 'EQUITY', 'USD', true),
    ('ELV', 'Elevance Health Inc.', 'EQUITY', 'USD', true),
    ('ISRG', 'Intuitive Surgical Inc.', 'EQUITY', 'USD', true),
    ('MDT', 'Medtronic plc', 'EQUITY', 'USD', true),
    ('SYK', 'Stryker Corp.', 'EQUITY', 'USD', true),
    ('REGN', 'Regeneron Pharmaceuticals Inc.', 'EQUITY', 'USD', true),
    ('VRTX', 'Vertex Pharmaceuticals Inc.', 'EQUITY', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('WMT', 'Walmart Inc.', 'EQUITY', 'USD', true),
    ('COST', 'Costco Wholesale Corp.', 'EQUITY', 'USD', true),
    ('PG', 'Procter & Gamble Co.', 'EQUITY', 'USD', true),
    ('KO', 'Coca-Cola Co.', 'EQUITY', 'USD', true),
    ('PEP', 'PepsiCo Inc.', 'EQUITY', 'USD', true),
    ('MCD', 'McDonald''s Corp.', 'EQUITY', 'USD', true),
    ('SBUX', 'Starbucks Corp.', 'EQUITY', 'USD', true),
    ('NKE', 'Nike Inc.', 'EQUITY', 'USD', true),
    ('HD', 'Home Depot Inc.', 'EQUITY', 'USD', true),
    ('LOW', 'Lowe''s Companies Inc.', 'EQUITY', 'USD', true),
    ('TGT', 'Target Corp.', 'EQUITY', 'USD', true),
    ('TJX', 'TJX Companies Inc.', 'EQUITY', 'USD', true),
    ('EL', 'Estee Lauder Companies Inc.', 'EQUITY', 'USD', true),
    ('CL', 'Colgate-Palmolive Co.', 'EQUITY', 'USD', true),
    ('KMB', 'Kimberly-Clark Corp.', 'EQUITY', 'USD', true),
    ('MDLZ', 'Mondelez International Inc.', 'EQUITY', 'USD', true),
    ('MO', 'Altria Group Inc.', 'EQUITY', 'USD', true),
    ('PM', 'Philip Morris International Inc.', 'EQUITY', 'USD', true),
    ('YUM', 'Yum! Brands Inc.', 'EQUITY', 'USD', true),
    ('CMG', 'Chipotle Mexican Grill Inc.', 'EQUITY', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('XOM', 'Exxon Mobil Corp.', 'EQUITY', 'USD', true),
    ('CVX', 'Chevron Corp.', 'EQUITY', 'USD', true),
    ('COP', 'ConocoPhillips', 'EQUITY', 'USD', true),
    ('SLB', 'Schlumberger NV', 'EQUITY', 'USD', true),
    ('EOG', 'EOG Resources Inc.', 'EQUITY', 'USD', true),
    ('MPC', 'Marathon Petroleum Corp.', 'EQUITY', 'USD', true),
    ('PSX', 'Phillips 66', 'EQUITY', 'USD', true),
    ('VLO', 'Valero Energy Corp.', 'EQUITY', 'USD', true),
    ('OXY', 'Occidental Petroleum Corp.', 'EQUITY', 'USD', true),
    ('WMB', 'Williams Companies Inc.', 'EQUITY', 'USD', true),
    ('BA', 'Boeing Co.', 'EQUITY', 'USD', true),
    ('CAT', 'Caterpillar Inc.', 'EQUITY', 'USD', true),
    ('GE', 'General Electric Co.', 'EQUITY', 'USD', true),
    ('HON', 'Honeywell International Inc.', 'EQUITY', 'USD', true),
    ('UPS', 'United Parcel Service Inc.', 'EQUITY', 'USD', true),
    ('RTX', 'RTX Corp.', 'EQUITY', 'USD', true),
    ('LMT', 'Lockheed Martin Corp.', 'EQUITY', 'USD', true),
    ('DE', 'Deere & Co.', 'EQUITY', 'USD', true),
    ('MMM', '3M Co.', 'EQUITY', 'USD', true),
    ('FDX', 'FedEx Corp.', 'EQUITY', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('F', 'Ford Motor Co.', 'EQUITY', 'USD', true),
    ('GM', 'General Motors Co.', 'EQUITY', 'USD', true),
    ('RIVN', 'Rivian Automotive Inc.', 'EQUITY', 'USD', true),
    ('LCID', 'Lucid Group Inc.', 'EQUITY', 'USD', true),
    ('ABNB', 'Airbnb Inc.', 'EQUITY', 'USD', true),
    ('BKNG', 'Booking Holdings Inc.', 'EQUITY', 'USD', true),
    ('MAR', 'Marriott International Inc.', 'EQUITY', 'USD', true),
    ('DAL', 'Delta Air Lines Inc.', 'EQUITY', 'USD', true),
    ('UAL', 'United Airlines Holdings Inc.', 'EQUITY', 'USD', true),
    ('LUV', 'Southwest Airlines Co.', 'EQUITY', 'USD', true),
    ('CCL', 'Carnival Corp.', 'EQUITY', 'USD', true),
    ('RCL', 'Royal Caribbean Group', 'EQUITY', 'USD', true),
    ('EA', 'Electronic Arts Inc.', 'EQUITY', 'USD', true),
    ('TTWO', 'Take-Two Interactive Software Inc.', 'EQUITY', 'USD', true),
    ('RBLX', 'Roblox Corp.', 'EQUITY', 'USD', true),
    ('SPOT', 'Spotify Technology SA', 'EQUITY', 'USD', true),
    ('PINS', 'Pinterest Inc.', 'EQUITY', 'USD', true),
    ('SNAP', 'Snap Inc.', 'EQUITY', 'USD', true),
    ('ROKU', 'Roku Inc.', 'EQUITY', 'USD', true),
    ('DDOG', 'Datadog Inc.', 'EQUITY', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('NET', 'Cloudflare Inc.', 'EQUITY', 'USD', true),
    ('CRWD', 'CrowdStrike Holdings Inc.', 'EQUITY', 'USD', true),
    ('ZS', 'Zscaler Inc.', 'EQUITY', 'USD', true),
    ('PANW', 'Palo Alto Networks Inc.', 'EQUITY', 'USD', true),
    ('FTNT', 'Fortinet Inc.', 'EQUITY', 'USD', true),
    ('MDB', 'MongoDB Inc.', 'EQUITY', 'USD', true),
    ('TEAM', 'Atlassian Corp.', 'EQUITY', 'USD', true),
    ('WDAY', 'Workday Inc.', 'EQUITY', 'USD', true),
    ('ZM', 'Zoom Video Communications Inc.', 'EQUITY', 'USD', true),
    ('DOCU', 'DocuSign Inc.', 'EQUITY', 'USD', true),
    ('OKTA', 'Okta Inc.', 'EQUITY', 'USD', true),
    ('TWLO', 'Twilio Inc.', 'EQUITY', 'USD', true),
    ('HUBS', 'HubSpot Inc.', 'EQUITY', 'USD', true),
    ('ADSK', 'Autodesk Inc.', 'EQUITY', 'USD', true),
    ('ANSS', 'Ansys Inc.', 'EQUITY', 'USD', true),
    ('ASML', 'ASML Holding NV', 'EQUITY', 'USD', true),
    ('TSM', 'Taiwan Semiconductor Manufacturing Co.', 'EQUITY', 'USD', true),
    ('MU', 'Micron Technology Inc.', 'EQUITY', 'USD', true),
    ('LRCX', 'Lam Research Corp.', 'EQUITY', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('AMAT', 'Applied Materials Inc.', 'EQUITY', 'USD', true),
    ('KLAC', 'KLA Corp.', 'EQUITY', 'USD', true),
    ('NXPI', 'NXP Semiconductors NV', 'EQUITY', 'USD', true),
    ('ADI', 'Analog Devices Inc.', 'EQUITY', 'USD', true),
    ('MRVL', 'Marvell Technology Inc.', 'EQUITY', 'USD', true),
    ('ON', 'ON Semiconductor Corp.', 'EQUITY', 'USD', true),
    ('SWKS', 'Skyworks Solutions Inc.', 'EQUITY', 'USD', true),
    ('DUK', 'Duke Energy Corp.', 'EQUITY', 'USD', true),
    ('SO', 'Southern Co.', 'EQUITY', 'USD', true),
    ('NEE', 'NextEra Energy Inc.', 'EQUITY', 'USD', true),
    ('AEP', 'American Electric Power Co.', 'EQUITY', 'USD', true),
    ('EXC', 'Exelon Corp.', 'EQUITY', 'USD', true),
    ('SRE', 'Sempra', 'EQUITY', 'USD', true),
    ('D', 'Dominion Energy Inc.', 'EQUITY', 'USD', true),
    ('PCG', 'PG&E Corp.', 'EQUITY', 'USD', true),
    ('AMT', 'American Tower Corp.', 'REIT', 'USD', true),
    ('PLD', 'Prologis Inc.', 'REIT', 'USD', true),
    ('CCI', 'Crown Castle Inc.', 'REIT', 'USD', true),
    ('EQIX', 'Equinix Inc.', 'REIT', 'USD', true),
    ('SPG', 'Simon Property Group Inc.', 'REIT', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('PSA', 'Public Storage', 'REIT', 'USD', true),
    ('O', 'Realty Income Corp.', 'REIT', 'USD', true),
    ('DLR', 'Digital Realty Trust Inc.', 'REIT', 'USD', true),
    ('WELL', 'Welltower Inc.', 'REIT', 'USD', true),
    ('AVB', 'AvalonBay Communities Inc.', 'REIT', 'USD', true),
    ('SPY', 'SPDR S&P 500 ETF Trust', 'ETF', 'USD', true),
    ('QQQ', 'Invesco QQQ Trust', 'ETF', 'USD', true),
    ('DIA', 'SPDR Dow Jones Industrial Average ETF', 'ETF', 'USD', true),
    ('IWM', 'iShares Russell 2000 ETF', 'ETF', 'USD', true),
    ('VTI', 'Vanguard Total Stock Market ETF', 'ETF', 'USD', true),
    ('VOO', 'Vanguard S&P 500 ETF', 'ETF', 'USD', true),
    ('VEA', 'Vanguard FTSE Developed Markets ETF', 'ETF', 'USD', true),
    ('VWO', 'Vanguard FTSE Emerging Markets ETF', 'ETF', 'USD', true),
    ('AGG', 'iShares Core U.S. Aggregate Bond ETF', 'ETF', 'USD', true),
    ('BND', 'Vanguard Total Bond Market ETF', 'ETF', 'USD', true),
    ('GLD', 'SPDR Gold Shares', 'ETF', 'USD', true),
    ('SLV', 'iShares Silver Trust', 'ETF', 'USD', true),
    ('USO', 'United States Oil Fund', 'ETF', 'USD', true),
    ('XLK', 'Technology Select Sector SPDR Fund', 'ETF', 'USD', true),
    ('XLF', 'Financial Select Sector SPDR Fund', 'ETF', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('XLE', 'Energy Select Sector SPDR Fund', 'ETF', 'USD', true),
    ('XLV', 'Health Care Select Sector SPDR Fund', 'ETF', 'USD', true),
    ('XLY', 'Consumer Discretionary Select Sector SPDR Fund', 'ETF', 'USD', true),
    ('XLP', 'Consumer Staples Select Sector SPDR Fund', 'ETF', 'USD', true),
    ('XLI', 'Industrial Select Sector SPDR Fund', 'ETF', 'USD', true),
    ('XLU', 'Utilities Select Sector SPDR Fund', 'ETF', 'USD', true),
    ('XLB', 'Materials Select Sector SPDR Fund', 'ETF', 'USD', true),
    ('XLRE', 'Real Estate Select Sector SPDR Fund', 'ETF', 'USD', true),
    ('ARKK', 'ARK Innovation ETF', 'ETF', 'USD', true),
    ('SMH', 'VanEck Semiconductor ETF', 'ETF', 'USD', true),
    ('BABA', 'Alibaba Group Holding Ltd.', 'EQUITY', 'USD', true),
    ('JD', 'JD.com Inc.', 'EQUITY', 'USD', true),
    ('PDD', 'PDD Holdings Inc.', 'EQUITY', 'USD', true),
    ('NIO', 'NIO Inc.', 'EQUITY', 'USD', true),
    ('SE', 'Sea Ltd.', 'EQUITY', 'USD', true),
    ('MELI', 'MercadoLibre Inc.', 'EQUITY', 'USD', true),
    ('SONY', 'Sony Group Corp.', 'EQUITY', 'USD', true),
    ('TM', 'Toyota Motor Corp.', 'EQUITY', 'USD', true),
    ('HMC', 'Honda Motor Co. Ltd.', 'EQUITY', 'USD', true),
    ('SAP', 'SAP SE', 'EQUITY', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('NVO', 'Novo Nordisk A/S', 'EQUITY', 'USD', true),
    ('SHEL', 'Shell plc', 'EQUITY', 'USD', true),
    ('BP', 'BP plc', 'EQUITY', 'USD', true),
    ('HSBC', 'HSBC Holdings plc', 'EQUITY', 'USD', true),
    ('TD', 'Toronto-Dominion Bank', 'EQUITY', 'USD', true),
    ('RY', 'Royal Bank of Canada', 'EQUITY', 'USD', true),
    ('BHP', 'BHP Group Ltd.', 'EQUITY', 'USD', true),
    ('RIO', 'Rio Tinto Group', 'EQUITY', 'USD', true),
    ('UL', 'Unilever plc', 'EQUITY', 'USD', true),
    ('DEO', 'Diageo plc', 'EQUITY', 'USD', true),
    ('BTI', 'British American Tobacco plc', 'EQUITY', 'USD', true),
    ('GSK', 'GSK plc', 'EQUITY', 'USD', true),
    ('AZN', 'AstraZeneca plc', 'EQUITY', 'USD', true),
    ('SNY', 'Sanofi SA', 'EQUITY', 'USD', true),
    ('NVS', 'Novartis AG', 'EQUITY', 'USD', true),
    ('RHHBY', 'Roche Holding AG', 'EQUITY', 'USD', true),
    ('SIEGY', 'Siemens AG', 'EQUITY', 'USD', true),
    ('VWAGY', 'Volkswagen AG', 'EQUITY', 'USD', true),
    ('MBGYY', 'Mercedes-Benz Group AG', 'EQUITY', 'USD', true),
    ('BMWYY', 'Bayerische Motoren Werke AG', 'EQUITY', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO instruments (symbol, name, asset_class, currency, tradable) VALUES
    ('COIN', 'Coinbase Global Inc.', 'EQUITY', 'USD', true),
    ('MSTR', 'MicroStrategy Inc.', 'EQUITY', 'USD', true),
    ('HOOD', 'Robinhood Markets Inc.', 'EQUITY', 'USD', true),
    ('SOFI', 'SoFi Technologies Inc.', 'EQUITY', 'USD', true),
    ('AFRM', 'Affirm Holdings Inc.', 'EQUITY', 'USD', true),
    ('UPST', 'Upstart Holdings Inc.', 'EQUITY', 'USD', true),
    ('DKNG', 'DraftKings Inc.', 'EQUITY', 'USD', true),
    ('CVNA', 'Carvana Co.', 'EQUITY', 'USD', true),
    ('ETSY', 'Etsy Inc.', 'EQUITY', 'USD', true),
    ('EBAY', 'eBay Inc.', 'EQUITY', 'USD', true),
    ('W', 'Wayfair Inc.', 'EQUITY', 'USD', true),
    ('CHWY', 'Chewy Inc.', 'EQUITY', 'USD', true),
    ('DASH', 'DoorDash Inc.', 'EQUITY', 'USD', true),
    ('LYFT', 'Lyft Inc.', 'EQUITY', 'USD', true),
    ('PATH', 'UiPath Inc.', 'EQUITY', 'USD', true),
    ('AI', 'C3.ai Inc.', 'EQUITY', 'USD', true),
    ('SMCI', 'Super Micro Computer Inc.', 'EQUITY', 'USD', true),
    ('DELL', 'Dell Technologies Inc.', 'EQUITY', 'USD', true),
    ('HPQ', 'HP Inc.', 'EQUITY', 'USD', true),
    ('HPE', 'Hewlett Packard Enterprise Co.', 'EQUITY', 'USD', true)
ON CONFLICT (symbol) DO NOTHING;
